### ISSUE TITLE
Stuck Adam

### ISSUE THREAD

**Issue by cartcarrot** [hdtf-owf/hdtf_issues#367]
### Expected Behavior

Adam should follow to the end and give his dialogue.

### Steps to Reproduce

open game
Go to level after Ravenholm
Finish level

### Detailed Description

![20230621204529_1](https://github.com/hdtf-owf/hdtf_issues/assets/131570698/cbbfce2e-bd42-46ca-87bb-37742be850a8)
![20230621204502_1](https://github.com/hdtf-owf/hdtf_issues/assets/131570698/59b5aa81-509d-4a45-afed-a22b943428ba)
Adam is just stuck and I'm pretty sure he didn't make any dialogue when you first meet him again.

### Operating System

Windows 10

**Comment by Terrrors** [comment]
Whoever made the map straight up forgot to add anything to do with adam moving lol, I fixed it recently.
