### ISSUE TITLE
Metro_02/Metro_03/Station Continuity Errors

### ISSUE THREAD

**Issue by halosammy** [hdtf-owf/hdtf_issues#368]
### Expected Behavior

Number of soldiers of a given type should roughly correlate with each other across maps.

### Steps to Reproduce

Count friendly NPCs between metro_3 and station.

### Detailed Description

Probably flew under the radar because it’s such a small issue.

Colonel Cue’s squad in metro_2 includes five generic soldier models with default camouflage, one of which is Larry with the different scarf.

At the beginning of metro_3, Cue’s group is down to three generic soldier models minus Larry. A second group waiting by the radio room consists of seven generic models wearing a different camouflage pattern. Notably, these seven are all marked as killable (suggesting they’re not supposed to survive the map’s firefight), whereas all of Cue’s men are invincible.

The next continuity error is from the fact that the second group only has six members when the firefight starts. Furthermore, at the start of station, the friendly NPCs are back to five generic soldiers (minus Larry) with the default camouflage pattern. In other words, the number of Cue’s men go back and forth in number while Larry and the second group of soldiers disappear entirely.

The fix should be as easy as increasing cue’s men in metro_3 by two and marking them as invincible while the second group dies. Either that or adding variety by marking two soldiers from the second group as invincible and then changing two soldiers in station to the corresponding camo pattern.

### Operating System

Windows 10

**Comment by Terrrors** [comment]
I actually mostly fixed this already, because I made a normal proper level transition between metro_3 and station I had to fix it so the amount of them stays the same. It just hasn't been recompiled and pushed to the dev build yet.

**Comment by halosammy** [comment]
In that case, I look forward to seeing it. Will close the issue until anything related comes up.
