### ISSUE TITLE
Cutscenes not running on owf_development_build

### ISSUE THREAD

**Issue by Mysteryman01** [hdtf-owf/hdtf_issues#4]
### Expected Behavior

1. Reach the trigger that starts the cutscene
2.Trigger fired
3. Cutscene works

### Steps to Reproduce

1. Reach the trigger that starts the cutscene
2.Trigger fired
3.Cutscene doesn't work

### Detailed Description

After updating the owf_development_build build on March 18, cutscenes stopped working for me, it says that the file with the cutscene was not found.

Example:
Failed to load background video 'media/background04.bik'!
Cannot play cutscene 'media/a0b0c0s0.bik' - file not found!
Cannot play cutscene 'media/a1c1p1s1.bik' - file not found!

### Operating System

Windows 10

**Comment by AnthonyPython** [comment]
This has already been fixed. mesa just didn't push the new update

**Comment by Nbc66** [comment]
already fixed thank you for the bug report
